### ISSUE TITLE
突然从炫酷的左右侧需求改成原生微信的，我发现指示器没法实现

### ISSUE THREAD

**Issue by crazies** [we-plugin/we-swiper#13]
那些花哨的事件都没什么用，因为自动轮播的时候任何事件都不会触发，请问如何解决这个尴尬的问题，我需要做指示器，肯定需要页面切换回调（哪怕自动播放）

**Comment by crazies** [comment]
我删除了runcallbacks判断 解决了问题
 typeof onSlideChangeEnd === 'function' && setTimeout(function () {

**Comment by dlhandsome** [comment]
@crazies 能否pr一下呢

**Comment by crazies** [comment]
请问什么是pr?

**Comment by dlhandsome** [comment]
@crazies 
![image](https://user-images.githubusercontent.com/16918885/34599260-2b6b1f38-f22c-11e7-8f49-375e8b44ccc8.png)看看能否一起改进下，尝试提交一个pull request
