### ISSUE TITLE
{{animationData}}具体指什么

### ISSUE THREAD

**Issue by hiboyluo** [we-plugin/we-swiper#19]
![image](https://user-images.githubusercontent.com/13565825/40150425-1ef070ae-59ac-11e8-8db1-aa65504a024a.png)

**Comment by ThickFive** [comment]
在对应 .js 文件中 data 设置的动画, 虽然在你自己的代码中看不到这个属性的具体设置, 但是它确实存在. 相当于 swiper 帮你创建一个 aWxAnimation, 然后 swiper.pageContext.setData({animationData: aWxAnimation}), 这些都是在 swiper 的代码里面完成的, 所以在你的 js 文件中是看不到的

**Comment by hiboyluo** [comment]
好的，谢谢
